"""
HDL Generator (Verilog/SystemVerilog)
Generates structural and behavioral HDL from circuit topology
"""

from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass
from enum import Enum


class HDLLanguage(Enum):
    VERILOG = "verilog"
    SYSTEMVERILOG = "systemverilog"
    VHDL = "vhdl"


@dataclass
class HDLModule:
    """HDL module representation"""
    name: str
    language: HDLLanguage
    ports: List[Dict[str, str]]  # {'name': 'input_a', 'direction': 'input', 'width': '1'}
    content: str
    dependencies: List[str] = None


class HDLGenerator:
    """Generate Verilog/SystemVerilog from circuit topology"""
    
    def __init__(self, language: HDLLanguage = HDLLanguage.SYSTEMVERILOG):
        self.language = language
        self.indent = "    "
    
    def generate_structural(
        self,
        components: List[Dict[str, Any]],
        nets: Dict[str, Any],
        module_name: str = "circuit_top"
    ) -> str:
        """
        Generate structural HDL (instantiates components)
        
        Args:
            components: List of circuit components
            nets: Network connectivity
            module_name: Name of top-level module
            
        Returns:
            HDL code as string
        """
        lines = []
        
        # Header comment
        lines.append("//")
        lines.append("// Synthra Generated HDL - Structural")
        lines.append(f"// Module: {module_name}")
        lines.append("//")
        lines.append("")
        
        # Module declaration
        ports = self._extract_ports(components, nets)
        lines.append(self._generate_module_header(module_name, ports))
        lines.append("")
        
        # Internal wire declarations
        lines.append(f"{self.indent}// Internal nets")
        for net_name in self._get_internal_nets(nets):
            lines.append(f"{self.indent}wire {net_name};")
        lines.append("")
        
        # Component instantiations
        lines.append(f"{self.indent}// Component instances")
        for i, comp in enumerate(components):
            inst_lines = self._generate_component_instance(comp, i)
            lines.extend([f"{self.indent}{l}" for l in inst_lines])
            lines.append("")
        
        lines.append("endmodule")
        
        return "\n".join(lines)
    
    def generate_behavioral(
        self,
        components: List[Dict[str, Any]],
        nets: Dict[str, Any],
        module_name: str = "circuit_behavioral"
    ) -> str:
        """
        Generate behavioral HDL (describes circuit function)
        Useful for digital logic only
        """
        lines = []
        
        # Header
        lines.append("//")
        lines.append("// Synthra Generated HDL - Behavioral")
        lines.append(f"// Module: {module_name}")
        lines.append("//")
        lines.append("")
        
        # Module declaration
        ports = self._extract_ports(components, nets)
        lines.append(self._generate_module_header(module_name, ports))
        lines.append("")
        
        # Generate behavioral logic for digital components
        logic_lines = self._generate_behavioral_logic(components, nets)
        lines.extend([f"{self.indent}{l}" for l in logic_lines])
        lines.append("")
        
        lines.append("endmodule")
        
        return "\n".join(lines)
    
    def generate_testbench(
        self,
        module_name: str,
        ports: List[Dict[str, str]],
        test_duration: int = 1000
    ) -> str:
        """
        Generate testbench for the circuit
        
        Args:
            module_name: Name of module under test
            ports: List of port definitions
            test_duration: Simulation time in ns
            
        Returns:
            Testbench HDL code
        """
        tb_name = f"{module_name}_tb"
        lines = []
        
        # Header
        lines.append("//")
        lines.append(f"// Testbench for {module_name}")
        lines.append("// Generated by Synthra")
        lines.append("//")
        lines.append("")
        
        # Timescale
        if self.language == HDLLanguage.SYSTEMVERILOG:
            lines.append("`timescale 1ns/1ps")
            lines.append("")
        
        # Module declaration
        lines.append(f"module {tb_name};")
        lines.append("")
        
        # Signal declarations
        lines.append(f"{self.indent}// Testbench signals")
        for port in ports:
            direction = port['direction']
            width = port.get('width', '1')
            name = port['name']
            
            # Invert direction for testbench
            if direction == 'input':
                sig_type = 'reg' if self.language == HDLLanguage.VERILOG else 'logic'
            else:
                sig_type = 'wire'
            
            if width == '1':
                lines.append(f"{self.indent}{sig_type} {name};")
            else:
                lines.append(f"{self.indent}{sig_type} [{width}-1:0] {name};")
        
        lines.append("")
        
        # DUT instantiation
        lines.append(f"{self.indent}// Device Under Test")
        lines.append(f"{self.indent}{module_name} dut (")
        
        port_connections = []
        for port in ports:
            port_connections.append(f".{port['name']}({port['name']})")
        
        lines.append(f"{self.indent}{self.indent}" + f",\n{self.indent}{self.indent}".join(port_connections))
        lines.append(f"{self.indent});")
        lines.append("")
        
        # Clock generation (if clock exists)
        if any(p['name'].lower() in ['clk', 'clock'] for p in ports):
            lines.append(f"{self.indent}// Clock generation")
            lines.append(f"{self.indent}always #5 clk = ~clk;")
            lines.append("")
        
        # Initial block
        lines.append(f"{self.indent}// Stimulus")
        lines.append(f"{self.indent}initial begin")
        lines.append(f"{self.indent}{self.indent}// Dump waveforms")
        lines.append(f'{self.indent}{self.indent}$dumpfile("{module_name}.vcd");')
        lines.append(f'{self.indent}{self.indent}$dumpvars(0, {tb_name});')
        lines.append("")
        
        # Initialize inputs
        lines.append(f"{self.indent}{self.indent}// Initialize inputs")
        for port in ports:
            if port['direction'] == 'input':
                if port['name'].lower() in ['clk', 'clock']:
                    lines.append(f"{self.indent}{self.indent}{port['name']} = 0;")
                else:
                    lines.append(f"{self.indent}{self.indent}{port['name']} = 0;")
        
        lines.append("")
        lines.append(f"{self.indent}{self.indent}// Wait and apply stimulus")
        lines.append(f"{self.indent}{self.indent}#10;")
        lines.append("")
        
        # Add test patterns
        lines.append(f"{self.indent}{self.indent}// Test patterns")
        lines.append(f"{self.indent}{self.indent}// TODO: Add specific test vectors")
        lines.append("")
        
        # End simulation
        lines.append(f"{self.indent}{self.indent}// End simulation")
        lines.append(f"{self.indent}{self.indent}#{test_duration};")
        lines.append(f"{self.indent}{self.indent}$finish;")
        lines.append(f"{self.indent}end")
        lines.append("")
        
        lines.append("endmodule")
        
        return "\n".join(lines)
    
    def _generate_module_header(
        self,
        module_name: str,
        ports: List[Dict[str, str]]
    ) -> str:
        """Generate module header with port list"""
        if not ports:
            return f"module {module_name}();"
        
        port_list = []
        for port in ports:
            direction = port['direction']
            width = port.get('width', '1')
            name = port['name']
            
            if width == '1':
                port_list.append(f"{direction} {name}")
            else:
                port_list.append(f"{direction} [{width}-1:0] {name}")
        
        # Format with proper indentation
        header = f"module {module_name} (\n"
        header += f"{self.indent}" + f",\n{self.indent}".join(port_list)
        header += "\n);"
        
        return header
    
    def _extract_ports(
        self,
        components: List[Dict[str, Any]],
        nets: Dict[str, Any]
    ) -> List[Dict[str, str]]:
        """Extract module ports from circuit"""
        ports = []
        
        # Look for power, ground, and I/O components
        for comp in components:
            comp_type = comp.get('class', comp.get('component_type', ''))
            
            # Voltage sources become inputs
            if comp_type in ['voltage_source', 'vcc_power']:
                ports.append({
                    'name': 'vcc',
                    'direction': 'input',
                    'width': '1'
                })
            
            # Ground
            if comp_type == 'ground':
                ports.append({
                    'name': 'gnd',
                    'direction': 'input',
                    'width': '1'
                })
        
        # If no ports found, add default clock and reset
        if not ports:
            ports.append({'name': 'clk', 'direction': 'input', 'width': '1'})
            ports.append({'name': 'rst_n', 'direction': 'input', 'width': '1'})
            ports.append({'name': 'out', 'direction': 'output', 'width': '1'})
        
        return ports
    
    def _get_internal_nets(self, nets: Dict[str, Any]) -> List[str]:
        """Get list of internal net names"""
        internal_nets = []
        
        for net_name, net_info in nets.items():
            if not net_name.lower() in ['vcc', 'gnd', 'ground', 'vdd', 'vss']:
                internal_nets.append(net_name)
        
        return internal_nets
    
    def _generate_component_instance(
        self,
        comp: Dict[str, Any],
        index: int
    ) -> List[str]:
        """Generate HDL instance for a component"""
        comp_type = comp.get('class', comp.get('component_type', 'unknown'))
        value = comp.get('value', comp.get('detected_text', ''))
        nodes = comp.get('nodes', [])
        
        lines = []
        
        # Comment
        lines.append(f"// {comp_type} - {value}")
        
        # For analog components, use behavioral black-box wrappers
        if comp_type == 'resistor':
            lines.append(f"resistor #(.R({self._parse_value(value, '10000')})) R{index} (")
            lines.append(f"    .p({nodes[0] if len(nodes) > 0 else 'net0'}),")
            lines.append(f"    .n({nodes[1] if len(nodes) > 1 else 'net1'})")
            lines.append(");")
        
        elif comp_type == 'capacitor':
            lines.append(f"capacitor #(.C({self._parse_value(value, '100e-9')})) C{index} (")
            lines.append(f"    .p({nodes[0] if len(nodes) > 0 else 'net0'}),")
            lines.append(f"    .n({nodes[1] if len(nodes) > 1 else 'net1'})")
            lines.append(");")
        
        elif 'logic_gate' in comp_type:
            gate_type = comp_type.split('_')[-1].upper()
            lines.append(f"{gate_type.lower()} U{index} (")
            lines.append(f"    .a({nodes[0] if len(nodes) > 0 else 'net0'}),")
            lines.append(f"    .b({nodes[1] if len(nodes) > 1 else 'net1'}),")
            lines.append(f"    .y({nodes[2] if len(nodes) > 2 else 'net_out'})")
            lines.append(");")
        
        else:
            lines.append(f"// TODO: Instance for {comp_type}")
        
        return lines
    
    def _generate_behavioral_logic(
        self,
        components: List[Dict[str, Any]],
        nets: Dict[str, Any]
    ) -> List[str]:
        """Generate behavioral logic for digital components"""
        lines = []
        
        lines.append("// Behavioral logic")
        lines.append("// TODO: Analyze circuit and generate behavioral equations")
        lines.append("")
        lines.append("assign out = 1'b0; // Placeholder")
        
        return lines
    
    def _parse_value(self, value: str, default: str) -> str:
        """Parse component value to numeric format"""
        if not value:
            return default
        
        # Convert engineering notation (10k, 100n, etc.)
        multipliers = {
            'p': '1e-12',
            'n': '1e-9',
            'u': '1e-6',
            'm': '1e-3',
            'k': '1e3',
            'M': '1e6',
            'G': '1e9'
        }
        
        import re
        match = re.match(r'(\d+\.?\d*)([pnumkMG]?)', value)
        if match:
            num = match.group(1)
            mult = match.group(2)
            if mult and mult in multipliers:
                return f"({num} * {multipliers[mult]})"
            return num
        
        return default


def generate_verilog(
    components: List[Dict[str, Any]],
    nets: Dict[str, Any],
    module_name: str = "circuit_top",
    structural: bool = True
) -> str:
    """Convenience function to generate Verilog"""
    generator = HDLGenerator(HDLLanguage.SYSTEMVERILOG)
    
    if structural:
        return generator.generate_structural(components, nets, module_name)
    else:
        return generator.generate_behavioral(components, nets, module_name)


def generate_testbench(
    module_name: str,
    ports: List[Dict[str, str]]
) -> str:
    """Convenience function to generate testbench"""
    generator = HDLGenerator(HDLLanguage.SYSTEMVERILOG)
    return generator.generate_testbench(module_name, ports)
