"""
SPICE Netlist Generator
Converts circuit topology to SPICE netlist format
"""

from typing import List, Dict, Any, Optional
from dataclasses import dataclass
import re


@dataclass
class SPICEComponent:
    """SPICE component representation"""
    designator: str  # R1, C2, Q3, etc.
    component_type: str
    nodes: List[str]  # Connected net names
    value: Optional[str] = None
    model: Optional[str] = None
    params: Optional[Dict[str, Any]] = None


class NetlistGenerator:
    """Generate SPICE netlists from circuit topology"""
    
    def __init__(self):
        self.component_counter = {
            'resistor': 0,
            'capacitor': 0,
            'inductor': 0,
            'diode': 0,
            'transistor_bjt': 0,
            'transistor_mosfet': 0,
            'voltage_source': 0,
            'current_source': 0,
        }
    
    def generate(
        self,
        components: List[Dict[str, Any]],
        nets: Dict[str, Any],
        title: str = "Synthra Generated Circuit",
        include_analysis: bool = True
    ) -> str:
        """
        Generate complete SPICE netlist
        
        Args:
            components: List of detected components with types and connections
            nets: Network connectivity information
            title: Circuit title comment
            include_analysis: Whether to include .tran/.ac analysis commands
            
        Returns:
            Complete SPICE netlist as string
        """
        lines = []
        
        # Title (must be first line)
        lines.append(f"* {title}")
        lines.append(f"* Generated by Synthra")
        lines.append("")
        
        # Component definitions
        lines.append("* Component Definitions")
        for comp in components:
            spice_line = self._component_to_spice(comp)
            if spice_line:
                lines.append(spice_line)
        
        lines.append("")
        
        # Models (if needed)
        model_lines = self._generate_models(components)
        if model_lines:
            lines.append("* Device Models")
            lines.extend(model_lines)
            lines.append("")
        
        # Analysis commands
        if include_analysis:
            lines.append("* Analysis")
            lines.append(".tran 1us 10ms")  # Default transient analysis
            lines.append(".control")
            lines.append("run")
            lines.append("write output.raw")
            lines.append(".endc")
            lines.append("")
        
        # End
        lines.append(".end")
        
        return "\n".join(lines)
    
    def _component_to_spice(self, comp: Dict[str, Any]) -> Optional[str]:
        """
        Convert component dict to SPICE line
        
        SPICE format:
        - Resistor: R<name> <node1> <node2> <value>
        - Capacitor: C<name> <node1> <node2> <value>
        - Inductor: L<name> <node1> <node2> <value>
        - Diode: D<name> <anode> <cathode> <model>
        - BJT: Q<name> <collector> <base> <emitter> <model>
        - MOSFET: M<name> <drain> <gate> <source> <bulk> <model>
        - Voltage: V<name> <pos> <neg> <DC/AC value>
        - Current: I<name> <from> <to> <DC/AC value>
        """
        comp_type = comp.get('class', comp.get('component_type', 'unknown'))
        value = comp.get('value', comp.get('detected_text', ''))
        nodes = comp.get('nodes', [])
        
        # Auto-generate designator if not provided
        designator = comp.get('designator')
        if not designator:
            designator = self._generate_designator(comp_type)
        
        # Ensure we have enough nodes
        if len(nodes) < 2:
            print(f"Warning: Component {designator} has insufficient node connections")
            return None
        
        # Generate SPICE line based on component type
        if comp_type == 'resistor':
            return f"R{designator} {nodes[0]} {nodes[1]} {value or '1k'}"
        
        elif comp_type == 'capacitor':
            return f"C{designator} {nodes[0]} {nodes[1]} {value or '100n'}"
        
        elif comp_type == 'inductor':
            return f"L{designator} {nodes[0]} {nodes[1]} {value or '1m'}"
        
        elif comp_type == 'diode' or comp_type == 'led':
            model = comp.get('model', 'D1N4148')
            return f"D{designator} {nodes[0]} {nodes[1]} {model}"
        
        elif 'bjt' in comp_type.lower():
            if len(nodes) < 3:
                return None
            model = comp.get('model', '2N2222' if 'npn' in comp_type.lower() else '2N2907')
            return f"Q{designator} {nodes[0]} {nodes[1]} {nodes[2]} {model}"
        
        elif 'mosfet' in comp_type.lower():
            if len(nodes) < 4:
                nodes.append(nodes[2])  # Use source as bulk if not specified
            model = comp.get('model', 'NMOS' if '_n' in comp_type.lower() else 'PMOS')
            return f"M{designator} {nodes[0]} {nodes[1]} {nodes[2]} {nodes[3]} {model}"
        
        elif comp_type == 'voltage_source' or comp_type == 'vcc_power':
            return f"V{designator} {nodes[0]} {nodes[1]} DC {value or '5'}"
        
        elif comp_type == 'current_source':
            return f"I{designator} {nodes[0]} {nodes[1]} DC {value or '1m'}"
        
        elif comp_type == 'ground':
            # Ground is typically node 0, no component line needed
            return None
        
        elif comp_type == 'op_amp':
            # Op-amp as subcircuit (simplified)
            if len(nodes) < 3:
                return None
            return f"X{designator} {nodes[0]} {nodes[1]} {nodes[2]} OPAMP"
        
        else:
            print(f"Warning: Unknown component type: {comp_type}")
            return f"* Unknown component: {designator} type={comp_type}"
    
    def _generate_designator(self, comp_type: str) -> str:
        """Generate unique component designator"""
        prefix_map = {
            'resistor': 'R',
            'capacitor': 'C',
            'inductor': 'L',
            'diode': 'D',
            'led': 'D',
            'transistor_bjt': 'Q',
            'transistor_mosfet': 'M',
            'voltage_source': 'V',
            'current_source': 'I',
            'op_amp': 'U',
            'ic': 'U',
        }
        
        prefix = prefix_map.get(comp_type, 'X')
        
        # Increment counter
        if comp_type not in self.component_counter:
            self.component_counter[comp_type] = 0
        
        self.component_counter[comp_type] += 1
        return f"{prefix}{self.component_counter[comp_type]}"
    
    def _generate_models(self, components: List[Dict[str, Any]]) -> List[str]:
        """Generate .model statements for components"""
        models = []
        added_models = set()
        
        for comp in components:
            comp_type = comp.get('class', comp.get('component_type', ''))
            
            # Generic diode model
            if ('diode' in comp_type or 'led' in comp_type) and 'D1N4148' not in added_models:
                models.append(".model D1N4148 D(IS=5.84n RS=0.7 BV=100 IBV=100u)")
                added_models.add('D1N4148')
            
            # Generic BJT models
            if 'bjt' in comp_type.lower():
                if 'npn' in comp_type.lower() and '2N2222' not in added_models:
                    models.append(".model 2N2222 NPN(IS=14.34f BF=255.9 VAF=74.03)")
                    added_models.add('2N2222')
                elif 'pnp' in comp_type.lower() and '2N2907' not in added_models:
                    models.append(".model 2N2907 PNP(IS=650.6f BF=231.7 VAF=115.7)")
                    added_models.add('2N2907')
            
            # Generic MOSFET models
            if 'mosfet' in comp_type.lower():
                if '_n' in comp_type.lower() and 'NMOS' not in added_models:
                    models.append(".model NMOS NMOS(LEVEL=1 VTO=0.7 KP=110u)")
                    added_models.add('NMOS')
                elif '_p' in comp_type.lower() and 'PMOS' not in added_models:
                    models.append(".model PMOS PMOS(LEVEL=1 VTO=-0.7 KP=50u)")
                    added_models.add('PMOS')
        
        return models
    
    def validate_netlist(self, netlist: str) -> Dict[str, Any]:
        """
        Validate SPICE netlist syntax
        
        Returns:
            Dict with 'valid' bool and 'errors' list
        """
        errors = []
        
        lines = netlist.strip().split('\n')
        
        # Check title line
        if not lines or not lines[0].startswith('*'):
            errors.append("First line must be a title comment (starting with *)")
        
        # Check end statement
        if not any('.end' in line.lower() for line in lines):
            errors.append("Missing .end statement")
        
        # Check for component definitions
        component_lines = [l for l in lines if l and not l.startswith('*') and not l.startswith('.')]
        if not component_lines:
            errors.append("No component definitions found")
        
        return {
            'valid': len(errors) == 0,
            'errors': errors,
            'warnings': [],
            'component_count': len(component_lines)
        }


def generate_spice_netlist(
    components: List[Dict[str, Any]],
    nets: Dict[str, Any],
    title: str = "Generated Circuit"
) -> str:
    """Convenience function to generate SPICE netlist"""
    generator = NetlistGenerator()
    return generator.generate(components, nets, title)
