"""
Advanced PDF Generator using LaTeX
Generates publication-quality circuit documentation PDFs
"""

from typing import Dict, List, Any, Optional
from pathlib import Path
import subprocess
import tempfile
from jinja2 import Template
import base64


# LaTeX template for circuit reports
LATEX_TEMPLATE = r"""
\documentclass[11pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\usepackage{minted}
\usepackage{pgfplots}
\usepackage{circuitikz}
\usepackage{hyperref}
\usepackage{geometry}
\usepackage{float}
\usepackage{booktabs}
\usepackage{fancyhdr}

\geometry{margin=1in}
\pgfplotsset{compat=1.18}

% Header/Footer
\pagestyle{fancy}
\fancyhf{}
\rhead{{{ title }}}
\lhead{Synthra Generated Report}
\rfoot{Page \thepage}

\title{{ "{{" }} {{ title }} {{ "}}" }}}
\author{{ "{{" }} Generated by Synthra {{ "}}" }}}
\date{{ "{{" }} \today {{ "}}" }}}

\begin{document}

\maketitle
\tableofcontents
\newpage

% ============================================================================
% ABSTRACT / SUMMARY
% ============================================================================
\section{Summary}

{{ summary }}

% ============================================================================
% SCHEMATIC
% ============================================================================
\section{Circuit Schematic}

{{ schematic_description }}

\begin{figure}[H]
    \centering
    {% if schematic_svg %}
    \includegraphics[width=0.9\textwidth]{{ "{{" }}schematic{{ "}}" }}}
    {% endif %}
    \caption{Auto-detected circuit schematic}
    \label{fig:schematic}
\end{figure}

% ============================================================================
% COMPONENT TABLE
% ============================================================================
\section{Bill of Materials}

\begin{table}[H]
\centering
\begin{tabular}{lllll}
\toprule
Designator & Type & Value & Footprint & Description \\
\midrule
{% for comp in components %}
{{ comp.designator }} & {{ comp.type }} & {{ comp.value }} & {{ comp.footprint }} & {{ comp.description }} \\
{% endfor %}
\bottomrule
\end{tabular}
\caption{Component list}
\label{tab:components}
\end{table}

% ============================================================================
% NETLIST
% ============================================================================
\section{SPICE Netlist}

The following SPICE netlist was automatically generated from the detected schematic:

\begin{minted}[fontsize=\small,breaklines]{spice}
{{ netlist_content }}
\end{minted}

% ============================================================================
% HDL CODE
% ============================================================================
{% if hdl_content %}
\section{HDL Representation}

The circuit has been translated to {{ hdl_language }} for digital simulation:

\begin{minted}[fontsize=\small,breaklines]{verilog}
{{ hdl_content }}
\end{minted}
{% endif %}

% ============================================================================
% SIMULATION RESULTS
% ============================================================================
\section{Simulation Results}

{{ simulation_description }}

{% if waveform_csv %}
\subsection{Transient Analysis}

\begin{figure}[H]
    \centering
    \begin{tikzpicture}
        \begin{axis}[
            width=0.9\textwidth,
            height=0.4\textwidth,
            xlabel={Time (s)},
            ylabel={Voltage (V)},
            grid=major,
            legend pos=north east
        ]
        {% for signal in waveform_signals %}
        \addplot table [x=time, y={{ signal }}, col sep=comma] {{ "{{" }}waveform_data{{ "}}" }}};
        \addlegendentry{{ "{{" }}{{ signal }}{{ "}}" }}}
        {% endfor %}
        \end{axis}
    \end{tikzpicture}
    \caption{Simulation waveforms}
    \label{fig:waveforms}
\end{figure}
{% endif %}

{% if waveform_image %}
\begin{figure}[H]
    \centering
    \includegraphics[width=0.9\textwidth]{{ "{{" }}waveform_plot{{ "}}" }}}
    \caption{Simulation waveforms}
    \label{fig:waveforms_plot}
\end{figure}
{% endif %}

% ============================================================================
% ANALYSIS & DISCUSSION
% ============================================================================
\section{Analysis}

{{ analysis_text }}

\subsection{Operating Point}

{% if operating_point %}
\begin{table}[H]
\centering
\begin{tabular}{ll}
\toprule
Node & Voltage (V) \\
\midrule
{% for node, voltage in operating_point.items() %}
{{ node }} & {{ "%.3f"|format(voltage) }} \\
{% endfor %}
\bottomrule
\end{tabular}
\caption{DC operating point}
\end{table}
{% endif %}

% ============================================================================
% REPRODUCTION INSTRUCTIONS
% ============================================================================
\section{Reproduction}

To reproduce this simulation:

\begin{enumerate}
    \item Install ngspice: \texttt{apt install ngspice} or \texttt{brew install ngspice}
    \item Save the netlist above to \texttt{circuit.cir}
    \item Run: \texttt{ngspice -b circuit.cir}
    \item View output: \texttt{gnuplot} or import CSV into your analysis tool
\end{enumerate}

% ============================================================================
% APPENDIX
% ============================================================================
\appendix

\section{Simulation Parameters}

\begin{itemize}
    \item Simulator: {{ simulator_name }}
    \item Analysis type: {{ analysis_type }}
    \item Time step: {{ time_step }}
    \item Duration: {{ duration }}
\end{itemize}

\section{Detection Metadata}

\begin{itemize}
    \item Components detected: {{ num_components }}
    \item Detection confidence: {{ detection_confidence }}
    \item Wire segments: {{ num_wires }}
    \item Net nodes: {{ num_nodes }}
\end{itemize}

\end{document}
"""


class PDFGenerator:
    """Generate publication-quality PDFs from circuit data"""
    
    def __init__(self, latex_compiler: str = "pdflatex"):
        """
        Initialize PDF generator
        
        Args:
            latex_compiler: "pdflatex" or "lualatex"
        """
        self.compiler = latex_compiler
        self.template = Template(LATEX_TEMPLATE)
    
    def generate(
        self,
        title: str,
        components: List[Dict[str, Any]],
        netlist: str,
        schematic_svg: Optional[str] = None,
        hdl_content: Optional[str] = None,
        waveforms: Optional[Dict[str, List[float]]] = None,
        summary: Optional[str] = None,
        analysis: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> bytes:
        """
        Generate PDF from circuit data
        
        Args:
            title: Document title
            components: List of component dicts
            netlist: SPICE netlist content
            schematic_svg: Path to schematic SVG (optional)
            hdl_content: Verilog/SystemVerilog code (optional)
            waveforms: Simulation waveform data (optional)
            summary: Circuit summary text (optional)
            analysis: Analysis text (optional)
            metadata: Additional metadata (optional)
            
        Returns:
            PDF file content as bytes
        """
        # Prepare template data
        template_data = {
            'title': title,
            'summary': summary or 'Auto-generated circuit report from Synthra.',
            'schematic_description': 'The circuit schematic was automatically detected from the input image using YOLOv8-based component detection and topology extraction.',
            'schematic_svg': schematic_svg is not None,
            'components': self._format_components(components),
            'netlist_content': netlist,
            'hdl_content': hdl_content,
            'hdl_language': 'SystemVerilog' if hdl_content else None,
            'simulation_description': 'The circuit was simulated using SPICE to analyze its transient and DC behavior.',
            'waveform_csv': waveforms is not None,
            'waveform_signals': list(waveforms.keys()) if waveforms else [],
            'waveform_image': False,  # Could add matplotlib plot
            'analysis_text': analysis or 'Simulation completed successfully. See waveforms above for detailed results.',
            'operating_point': metadata.get('operating_point') if metadata else None,
            'simulator_name': metadata.get('simulator', 'ngspice') if metadata else 'ngspice',
            'analysis_type': metadata.get('analysis_type', 'transient') if metadata else 'transient',
            'time_step': metadata.get('time_step', '1us') if metadata else '1us',
            'duration': metadata.get('duration', '10ms') if metadata else '10ms',
            'num_components': len(components),
            'detection_confidence': metadata.get('confidence', 0.85) if metadata else 0.85,
            'num_wires': metadata.get('num_wires', 0) if metadata else 0,
            'num_nodes': metadata.get('num_nodes', 0) if metadata else 0,
        }
        
        # Render LaTeX
        latex_content = self.template.render(**template_data)
        
        # Compile to PDF
        pdf_bytes = self._compile_latex(
            latex_content,
            schematic_svg=schematic_svg,
            waveforms=waveforms
        )
        
        return pdf_bytes
    
    def _format_components(self, components: List[Dict[str, Any]]) -> List[Dict[str, str]]:
        """Format components for LaTeX table"""
        formatted = []
        
        for comp in components:
            formatted.append({
                'designator': comp.get('designator', 'X?'),
                'type': comp.get('class', comp.get('component_type', 'Unknown')),
                'value': comp.get('value', comp.get('detected_text', 'N/A')),
                'footprint': comp.get('footprint', 'Generic'),
                'description': comp.get('description', '-')
            })
        
        return formatted
    
    def _compile_latex(
        self,
        latex_content: str,
        schematic_svg: Optional[str] = None,
        waveforms: Optional[Dict[str, List[float]]] = None
    ) -> bytes:
        """
        Compile LaTeX to PDF
        
        Returns:
            PDF bytes
        """
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            
            # Write LaTeX file
            tex_file = tmpdir_path / "document.tex"
            tex_file.write_text(latex_content)
            
            # Copy schematic if provided
            if schematic_svg:
                svg_dest = tmpdir_path / "schematic.svg"
                if Path(schematic_svg).exists():
                    import shutil
                    shutil.copy(schematic_svg, svg_dest)
            
            # Write waveform CSV if provided
            if waveforms:
                self._write_waveform_csv(tmpdir_path / "waveform_data.csv", waveforms)
            
            # Compile LaTeX (need multiple passes for TOC)
            try:
                for _ in range(2):  # Two passes for TOC and references
                    result = subprocess.run(
                        [
                            self.compiler,
                            "-shell-escape",  # For minted
                            "-interaction=nonstopmode",
                            "document.tex"
                        ],
                        cwd=tmpdir_path,
                        capture_output=True,
                        text=True,
                        timeout=60
                    )
                
                # Read PDF
                pdf_file = tmpdir_path / "document.pdf"
                if pdf_file.exists():
                    return pdf_file.read_bytes()
                else:
                    raise Exception(f"PDF compilation failed:\n{result.stderr}")
            
            except subprocess.TimeoutExpired:
                raise Exception("LaTeX compilation timeout")
            except Exception as e:
                raise Exception(f"LaTeX compilation error: {str(e)}")
    
    def _write_waveform_csv(self, path: Path, waveforms: Dict[str, List[float]]):
        """Write waveform data to CSV for pgfplots"""
        import csv
        
        # Assume first key is time
        keys = list(waveforms.keys())
        
        with open(path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(keys)
            
            # Write data rows
            num_points = len(waveforms[keys[0]])
            for i in range(num_points):
                row = [waveforms[k][i] for k in keys]
                writer.writerow(row)


def generate_pdf(
    title: str,
    components: List[Dict[str, Any]],
    netlist: str,
    **kwargs
) -> bytes:
    """Convenience function to generate PDF"""
    generator = PDFGenerator()
    return generator.generate(title, components, netlist, **kwargs)
